image: hashicorp/terraform:1.0.0

pipelines:
  default:
    - step:
        name: Plan
        caches:
          - terraform
        script:
          - terraform init
          - terraform plan -var-file="env/dev.tfvars"
    - step:
        name: Apply
        caches:
          - terraform
        script:
          - terraform init
          - terraform apply -var-file="env/dev.tfvars" -auto-approve
        branches:
          - develop
